tasks:
  - name: install-dependencies
    init: |
      docker pull cassandra:4
      pip install -U cqlsh
      curl -Ls "https://dtsx.io/get-astra-cli" | bash > instal-cli.log
    command: | 
      chmod 700 ./scripts/start-scenario.sh
      ./scripts/start-scenario.sh
ports:
  - port: 9042
    onOpen: ignore  
github:
  prebuilds:
    main: true
vscode:
  extensions:
    - https://github.com/HadesArchitect/katapod/releases/download/0.4.0/katapod-0.4.0.vsix
