tasks:
  - name: install-dependencies
    init: |
      curl -Ls "https://dtsx.io/get-astra-cli" | bash
      echo "Astra Cli Installed"
      docker pull cassandra:4
      echo "Docker installed"
      pip install -U cqlsh
      echo "Cqlsh installed"
      chmod 700 ./scripts/start-scenario.sh
    command: | 
      ./scripts/start-scenario.sh
ports:
  - port: 9042
    onOpen: ignore  
github:
  prebuilds:
    main: true
vscode:
  extensions:
    - https://github.com/HadesArchitect/katapod/releases/download/0.4.0/katapod-0.4.0.vsix
